version: '3.3'

services:
  traefik:
    command:
    - --api
    - --providers.docker
    - --providers.docker.exposedByDefault=true
    - --entrypoints.httpsecure.address=:443
    container_name: traefik
    restart: on-failure:5
    environment:
      DO_AUTH_TOKEN: '{{CTX_DIGITALOCEAN_TOKEN}}'
      TRAEFIK_ACCESSLOG: "true"
      TRAEFIK_ACCESSLOG_FILEPATH: /var/log/traefik_access.log
      TRAEFIK_LOG: "true"
    image: traefik:v2.0
    labels:
      traefik.http.middlewares.api_auth.basicauth.users: '{{TRAEFIK_WC_API_BASICAUTH}}'
      traefik.http.routers.api.entrypoints: httpsecure
      traefik.http.routers.api.middlewares: api_auth
      traefik.http.routers.api.rule: Host(`{{TRAEFIK_WC_API_HOSTNAME}}`)
      traefik.http.routers.api.service: api@internal
      traefik.http.routers.api.tls: ''
      traefik.tls.stores.default.defaultCertificate: ''
    ports:
    - published: 443
      target: 443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro

  weechat:
    container_name: weechat
    depends_on:
    - traefik
    restart: on-failure:5
    environment:
      UID: '1000'
      GID: '1000'
    image: danackerson/weechat
    labels:
      traefik.http.routers.web.rule: Host(`{{WEECHAT_HOSTNAME}}`)
    ports:
    - target: 9001
    volumes:
    - "/home/core/weechat:/weechat"

networks:
  default:
    external:
      name: web
