checkNewVersion = true
logLevel = "INFO"
defaultEntryPoints = ["https"]

[traefikLog]
  filePath = "/var/log/traefik/traefik.log"

[docker]
  endpoint = "unix:///var/run/docker.sock"
  domain = "ackerson.de"
  exposedByDefault = false

[entryPoints]
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.forwardedHeaders]
      trustedIPs = ["127.1.1.1/32"]
    [entryPoints.https.tls]

#[acme]
#email = "dan@ackerson.de"
#storage = "acme.json"
#entrypoint = "https"
#[acme.dnsChallenge]
#  provider = "digitalocean"
#  delayBeforeCheck = 10
#[[acme.domains]]
#  main = "${WEECHAT_HOSTNAME}"
